<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-21T18:35:43 IST" name="Suite" finished-at="2024-08-21T18:35:44 IST" duration-ms="870">
    <groups>
      <group name="Regression">
        <method signature="c1LoginTC.employeeLoginTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC@76012793]" name="employeeLoginTest" class="com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2024-08-21T18:35:43 IST" name="Test" finished-at="2024-08-21T18:35:44 IST" duration-ms="870">
      <class name="com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC">
        <test-method is-config="true" signature="openBrowser12()[pri:0, instance:com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC@76012793]" started-at="2024-08-21T18:35:43 IST" name="openBrowser12" finished-at="2024-08-21T18:35:43 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser12 -->
        <test-method signature="employeeLoginTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC@76012793]" started-at="2024-08-21T18:35:43 IST" name="employeeLoginTest" data-provider="LoginPageDS" finished-at="2024-08-21T18:35:44 IST" duration-ms="822" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC.employeeLoginTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: employeeLoginTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4])
Arguments: [(java.lang.String) VerifiedEmail,(java.lang.String) krunal@hashtaginfosystem.com,(java.lang.String) Password has been sent successfully]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC.employeeLoginTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException,java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: employeeLoginTest([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4])
Arguments: [(java.lang.String) VerifiedEmail,(java.lang.String) krunal@hashtaginfosystem.com,(java.lang.String) Password has been sent successfully]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:915)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- employeeLoginTest -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC@76012793]" started-at="2024-08-21T18:35:44 IST" name="closeBrowser" finished-at="2024-08-21T18:35:44 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.hashTagMIS.Test.EmployeeUC.c1Login.c1LoginTC -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
