<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N42I4EB" failures="2" tests="8" name="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" time="53.335" errors="0" timestamp="2024-08-22T14:03:46 IST" skipped="0">
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="6.197"/>
  <system-out>
    <![CDATA[Alpha=>Department added successfully!<====>Department added successfully!]]>
  </system-out>
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="6.091"/>
  <system-out>
    <![CDATA[Positive Min=>Department added successfully!<====>Department added successfully!]]>
  </system-out>
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="6.261"/>
  <system-out>
    <![CDATA[Alphanum=>Department added successfully!<====>Department added successfully!]]>
  </system-out>
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="6.034">
    <failure message="The following asserts failed:
	Num =&gt; Toast message does not match the expected message. expected [null] but found [Department added successfully!],
	Department list should not contain: 65444 expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Num => Toast message does not match the expected message. expected [null] but found [Department added successfully!],
Department list should not contain: 65444 expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC.AddDepartmentFunctionalTest(Ad1DepartmentFunctionalTC.java:117)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- AddDepartmentFunctionalTest -->
  <system-out>
    <![CDATA[Num=>Department added successfully!<====>null]]>
  </system-out>
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="6.116"/>
  <system-out>
    <![CDATA[Text=>Department added successfully!<====>Department added successfully!]]>
  </system-out>
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="6.184"/>
  <system-out>
    <![CDATA[Duplicate=>Department already exists<====>Department already exists]]>
  </system-out>
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="10.371"/>
  <system-out>
    <![CDATA[Negative Min=>null<====>null]]>
  </system-out>
  <testcase classname="com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC" name="AddDepartmentFunctionalTest" time="6.081">
    <failure message="The following asserts failed:
	SpecialChar =&gt; Toast message does not match the expected message. expected [null] but found [Department added successfully!],
	Department list should not contain: /,&quot;.&#039;!@#$_*^&amp; expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
SpecialChar => Toast message does not match the expected message. expected [null] but found [Department added successfully!],
Department list should not contain: /,".'!@#$_*^& expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC.AddDepartmentFunctionalTest(Ad1DepartmentFunctionalTC.java:117)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- AddDepartmentFunctionalTest -->
  <system-out>
    <![CDATA[SpecialChar=>Department added successfully!<====>null]]>
  </system-out>
</testsuite> <!-- com.hashTagMIS.Test.AdminUC.A1Department.Ad1DepartmentFunctionalTC -->
